In [1]:
import pandas as pd

print(pd.__version__)

3.0.6

In [3]:
Customers  = pd.read_csv("..//data/Customers.csv")
Products = pd.read_csv("../data/Products.csv")
Orders = pd.read_csv("../data/Orders.csv")
Order_Details = pd.read_csv("../data/Order_Details.csv")
Targets = pd.read_csv("../data/Targets.csv")

Copies Of dataset for cleaning

In [4]:
Customers_clean = Customers.copy()
Products_clean = Products.copy()
Orders_clean = Orders.copy()
Order_details_clean = Order_Details.copy()
Targets_clean = Targets.copy()

Check missing values in all datasets

In [8]:


print("Customers Missing Values:")
print(Customers_clean.isna().sum())

print("\nProducts Missing Values:")
print(Products_clean.isna().sum())

print("\nOrders Missing Values:")
print(Orders_clean.isna().sum())

print("\nOrder Details Missing Values:")
print(Order_details_clean.isna().sum())

print("\nTargets Missing Values:")
print(Targets_clean.isna().sum())

Customers Missing Values:
Customer_ID      0
Customer_Name    0
Gender           0
Age              0
City             0
State            0
Region           0
dtype: int64

Products Missing Values:
Product_ID       0
Product_Name     0
Category         0
Sub_Category     0
Brand            0
Cost_Price       0
Selling_Price    0
dtype: int64

Orders Missing Values:
Order_ID          0
Order_Date        0
Customer_ID       0
Payment_Method    0
Order_Status      0
Year              0
Month_Name        0
Quarter           0
Day               0
Weekday           0
Month             0
Region            0
dtype: int64

Order Details Missing Values:
Order_ID           0
Product_ID         0
Quantity           0
Discount           0
Selling_Price      0
Cost_Price         0
Gross_Sales        0
Discount_Amount    0
Net_Sales          0
Total_Cost         0
Profit             0
Profit_Margin      0
Customer_ID        0
Order_Date         0
Month              0
Month_start        0
Region             0
Category           0
dtype: int64

Targets Missing Values:
Month            0
Region           0
Sales_Target     0
Profit_Target    0
dtype: int64

Total missing values in each dataset

In [10]:

print("Customers:", Customers_clean.isna().sum().sum())
print("Products:", Products_clean.isna().sum().sum())
print("Orders:", Orders_clean.isna().sum().sum())
print("Order Details:", Order_details_clean.isna().sum().sum())
print("Targets:", Targets_clean.isna().sum().sum())

Customers: 0
Products: 0
Orders: 0
Order Details: 0
Targets: 0

 Check data types of all datasets

In [14]:

print("Customers Data Types:")
print(Customers_clean.dtypes)

print("\nProducts Data Types:")
print(Products_clean.dtypes)

print("\nTargets Data Types:")
print(Targets_clean.dtypes)

Customers Data Types:
Customer_ID        str
Customer_Name      str
Gender             str
Age              int64
City               str
State              str
Region             str
dtype: object

Products Data Types:
Product_ID         str
Product_Name       str
Category           str
Sub_Category       str
Brand              str
Cost_Price       int64
Selling_Price    int64
dtype: object

Targets Data Types:
Month              str
Region             str
Sales_Target     int64
Profit_Target    int64
dtype: object

In [16]:
print("\nOrders Data Types:")
print(Orders_clean.dtypes)

Orders Data Types:
Order_ID            str
Order_Date          str
Customer_ID         str
Payment_Method      str
Order_Status        str
Year              int64
Month_Name        int64
Quarter             str
Day               int64
Weekday             str
Month               str
Region              str
dtype: object

In [17]:
print("\nOrder Details Data Types:")
print(Order_details_clean.dtypes)

Order Details Data Types:
Order_ID               str
Product_ID             str
Quantity             int64
Discount           float64
Selling_Price        int64
Cost_Price           int64
Gross_Sales          int64
Discount_Amount    float64
Net_Sales          float64
Total_Cost           int64
Profit             float64
Profit_Margin      float64
Customer_ID            str
Order_Date             str
Month                  str
Month_start            str
Region                 str
Category               str
dtype: object

Convert Order_Date in Orders table

In [ ]:

Orders_clean["Order_Date"] = pd.to_datetime(
    Orders_clean["Order_Date"],
    format="%Y-%m-%d",
    errors="coerce"
)

Convert Order_Date in Order Details table

In [20]:

Order_details_clean["Order_Date"] = pd.to_datetime(
    Order_details_clean["Order_Date"],
    format="%Y-%m-%d",
    errors="coerce"
)

Verify the Conversion

In [21]:

print("Orders Order_Date Type:")
print(Orders_clean["Order_Date"].dtype)

print("\nOrder Details Order_Date Type:")
print(Order_details_clean["Order_Date"].dtype)

Orders Order_Date Type:
datetime64[s]

Order Details Order_Date Type:
datetime64[us]

Step 7:Verify Data Conversion

 Verify missing dates after conversion

In [23]:

print("Orders Missing Dates:")
print(Orders_clean["Order_Date"].isna().sum())

print("\nOrder Details Missing Dates:")
print(Order_details_clean["Order_Date"].isna().sum())

Orders Missing Dates:
400000

Order Details Missing Dates:
0

Check the date range

In [24]:

print("Orders Date Range:")
print(Orders_clean["Order_Date"].min())
print(Orders_clean["Order_Date"].max())

print("\nOrder Details Date Range:")
print(Order_details_clean["Order_Date"].min())
print(Order_details_clean["Order_Date"].max())

Orders Date Range:
NaT
NaT

Order Details Date Range:
2022-01-01 00:00:00
2025-12-31 00:00:00

Step 8: Investigate Orders Date Conversion

Reset Orders clean data

In [27]:
Orders_clean = Orders.copy()

Check Original Date Values

In [29]:
print("Original Orders Date Values:")
display(Orders["Order_Date"].head(10))

print("\nOriginal Data Type:")
print(Orders["Order_Date"].dtype)

print("\nOriginal Missing Values:")
print(Orders["Order_Date"].isna().sum())

Original Orders Date Values:

0    15-12-2023
1    06-06-2023
2    14-06-2023
3    22-09-2023
4    17-11-2025
5    16-06-2024
6    16-01-2022
7    03-01-2022
8    02-06-2023
9    29-10-2023
Name: Order_Date, dtype: str

Original Data Type:
str

Original Missing Values:
0

Check Different Date Formats

In [30]:
print("Unique Date Examples:")
print(Orders["Order_Date"].dropna().unique()[:20])

Unique Date Examples:
<StringArray>
['15-12-2023', '06-06-2023', '14-06-2023', '22-09-2023', '17-11-2025',
 '16-06-2024', '16-01-2022', '03-01-2022', '02-06-2023', '29-10-2023',
 '27-03-2023', '04-03-2024', '20-02-2025', '12-08-2024', '08-09-2025',
 '19-05-2023', '18-05-2023', '16-08-2022', '31-07-2025', '14-11-2022']
Length: 20, dtype: str

*Problem*


Orders dates are in DD-MM-YYYY format, but we used %Y-%m-%d, which caused all dates to become NaT.

Step 8: Fix Orders Date Conversion

In [31]:
Orders_clean["Order_Date"] = pd.to_datetime(
    Orders_clean["Order_Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

Verify Orders date conversion

In [32]:
print("Orders Data Type:")
print(Orders_clean["Order_Date"].dtype)

print("\nOrders Missing Dates:")
print(Orders_clean["Order_Date"].isna().sum())

print("\nOrders Date Range:")
print(Orders_clean["Order_Date"].min())
print(Orders_clean["Order_Date"].max())

Orders Data Type:
datetime64[us]

Orders Missing Dates:
0

Orders Date Range:
2022-01-01 00:00:00
2025-12-31 00:00:00

Step 9: Verify Both Tables

In [33]:
# Final date verification

print("Orders Missing Dates:",
      Orders_clean["Order_Date"].isna().sum())

print("Order Details Missing Dates:",
      Order_details_clean["Order_Date"].isna().sum())

Orders Missing Dates: 0
Order Details Missing Dates: 0

Step 10: Check Numeric Columns

Why is this important?

Numeric columns are required for calculations such as:

Total Sales

Total Cost

Profit

Quantity

Discount

Profit Margin

Check numeric columns

In [34]:
print("Products Numeric Columns:")
print(Products_clean[
    ["Cost_Price", "Selling_Price"]
].dtypes)

print("\nOrder Details Numeric Columns:")
print(Order_details_clean[
    [
        "Quantity",
        "Discount",
        "Selling_Price",
        "Cost_Price",
        "Gross_Sales",
        "Discount_Amount",
        "Net_Sales",
        "Total_Cost",
        "Profit",
        "Profit_Margin"
    ]
].dtypes)

Products Numeric Columns:
Cost_Price       int64
Selling_Price    int64
dtype: object

Order Details Numeric Columns:
Quantity             int64
Discount           float64
Selling_Price        int64
Cost_Price           int64
Gross_Sales          int64
Discount_Amount    float64
Net_Sales          float64
Total_Cost           int64
Profit             float64
Profit_Margin      float64
dtype: object

Check Numeric Values

In [36]:
# Display statistical summary of numeric columns

print("Products Summary:")
display(Products_clean.describe())

print("\nOrder Details Summary:")
display(Order_details_clean.describe())

Products Summary:

        Cost_Price  Selling_Price
count  1392.000000    1392.000000
mean    215.851293     285.369253
std     241.038023     323.031850
min       5.000000      10.000000
25%      60.000000      80.000000
50%     130.000000     170.000000
75%     271.250000     357.750000
max    1770.000000    2403.000000

Order Details Summary:

,Quantity,Discount,Selling_Price,Cost_Price,Gross_Sales,Discount_Amount,Net_Sales,Total_Cost,Profit,Profit_Margin,Order_Date
count,1.019516e+06,1.019516e+06,1.019516e+06,1.019516e+06,1.019516e+06,1.019516e+06,1.019516e+06,1.019516e+06,1.019516e+06,1.019516e+06,1019516
mean,1.703572e+00,6.500153e-02,2.484393e+02,1.928705e+02,4.005277e+02,2.603102e+01,3.744967e+02,3.117879e+02,6.270878e+01,1.713145e-01,2024-03-29 05:10:55.920652
min,1.000000e+00,0.000000e+00,1.000000e+01,5.000000e+00,1.000000e+01,0.000000e+00,7.500000e+00,5.000000e+00,-1.142000e+03,-3.492063e-01,2022-01-01 00:00:00
25%,1.000000e+00,0.000000e+00,6.500000e+01,5.000000e+01,1.000000e+02,0.000000e+00,9.000000e+01,7.500000e+01,1.000000e+01,1.000000e-01,2023-04-25 00:00:00
50%,1.000000e+00,5.000000e-02,1.500000e+02,1.200000e+02,2.220000e+02,7.000000e+00,2.090000e+02,1.750000e+02,2.950000e+01,1.700000e-01,2024-05-10 00:00:00
75%,2.000000e+00,1.000000e-01,3.200000e+02,2.350000e+02,5.100000e+02,2.775000e+01,4.750000e+02,4.000000e+02,7.500000e+01,2.500000e-01,2025-03-30 00:00:00
max,5.000000e+00,3.000000e-01,2.403000e+03,1.770000e+03,8.640000e+03,1.620000e+03,8.640000e+03,6.760000e+03,2.664000e+03,5.000000e-01,2025-12-31 00:00:00
std,9.484181e-01,6.643612e-02,2.732606e+02,2.131841e+02,5.088521e+02,5.422104e+01,4.776463e+02,4.021610e+02,1.035539e+02,1.115975e-01,NaN

Step 11: Check Invalid Numeric Values

Why do we check this?

Business data should follow logical rules:

Quantity should be greater than 0.

Prices should not be negative.

Discount should be between 0 and 1 (if stored as a decimal).

Cost and sales values should be valid.

Cheak Negative Values

In [41]:
print("Negative Quantity:")
print((Order_details_clean["Quantity"] < 0).sum())

print("\nNegative Selling Price:")
print((Order_details_clean["Selling_Price"] < 0).sum())

print("\nNegative Cost Price:")
print((Order_details_clean["Cost_Price"] < 0).sum())

print("\nNegative Discount:")
print((Order_details_clean["Discount"] < 0).sum())

Negative Quantity:
0

Negative Selling Price:
0

Negative Cost Price:
0

Negative Discount:
0

Cheak Discount Range

In [42]:
print("Minimum Discount:")
print(Order_details_clean["Discount"].min())

print("\nMaximum Discount:")
print(Order_details_clean["Discount"].max())

Minimum Discount:
0.0

Maximum Discount:
0.3

Check Quantity and Price Minimums

In [44]:
print("Minimum Quantity:")
print(Order_details_clean["Quantity"].min())

print("\nMinimum Selling Price:")
print(Order_details_clean["Selling_Price"].min())

print("\nMinimum Cost Price:")
print(Order_details_clean["Cost_Price"].min())

Minimum Quantity:
1

Minimum Selling Price:
10

Minimum Cost Price:
5

Step 12: Check Text Columns for Inconsistent Values

In [ ]:
# We want to identify things like:

# Male
# male
# MALE

Check Important Categories

In [45]:
print("Gender:")
print(Customers_clean["Gender"].unique())

print("\nRegion:")
print(Customers_clean["Region"].unique())

print("\nProduct Category:")
print(Products_clean["Category"].unique())

print("\nProduct Sub-Category:")
print(Products_clean["Sub_Category"].unique())

print("\nPayment Method:")
print(Orders_clean["Payment_Method"].unique())

print("\nOrder Status:")
print(Orders_clean["Order_Status"].unique())

Gender:
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

Region:
<StringArray>
['Central', 'West', 'East', 'North', 'South']
Length: 5, dtype: str

Product Category:
<StringArray>
['Fruits & Vegetables',   'Dairy & Breakfast',           'Beverages',
              'Snacks',       'Packaged Food',             'Staples',
              'Bakery',         'Frozen Food',       'Personal Care',
    'Beauty & Hygiene',           'Home Care',     'Household Items',
           'Baby Care',            'Pet Care']
Length: 14, dtype: str

Product Sub-Category:
<StringArray>
[     'Fresh Fruits',        'Vegetables',      'Leafy Greens',
              'Milk',     'Curd & Yogurt',   'Butter & Cheese',
         'Breakfast',       'Soft Drinks',            'Juices',
      'Tea & Coffee',             'Water',             'Chips',
           'Namkeen',          'Biscuits',      'Nuts & Seeds',
     'Instant Foods',  'Sauces & Spreads',      'Ready to Eat',
 'Canned & Packaged',              'Rice',             'Flour',
            'Pulses',              'Oils',            'Spices',
             'Bread',             'Cakes',           'Cookies',
     'Indian Bakery',     'Frozen Snacks', 'Frozen Vegetables',
   'Frozen Desserts',       'Bath & Body',         'Hair Care',
         'Oral Care',    'Men's Grooming',         'Skin Care',
            'Makeup',  'Feminine Hygiene',         'Fragrance',
           'Laundry',          'Cleaning',          'Air Care',
           'Kitchen',           'Storage',         'Utilities',
           'Diapers',         'Baby Food',      'Baby Hygiene',
          'Dog Food',          'Cat Food',       'Pet Hygiene']
Length: 51, dtype: str

Payment Method:
<StringArray>
['Credit Card', 'UPI', 'Wallet', 'Cash', 'Debit Card', 'Net Banking']
Length: 6, dtype: str

Order Status:
<StringArray>
['Delivered', 'Cancelled', 'Pending', 'Returned', 'Failed']
Length: 5, dtype: str

Check Number of Unique Values

In [47]:
print("Gender:", Customers_clean["Gender"].nunique())
print("Region:", Customers_clean["Region"].nunique())
print("Category:", Products_clean["Category"].nunique())
print("Sub-Category:", Products_clean["Sub_Category"].nunique())
print("Payment Method:", Orders_clean["Payment_Method"].nunique())
print("Order Status:", Orders_clean["Order_Status"].nunique())

Gender: 2
Region: 5
Category: 14
Sub-Category: 51
Payment Method: 6
Order Status: 5

Step 13: Clean Text Columns

Why? Extra spaces can cause problems when filtering, grouping, or joining data.

In [49]:
# Remove leading and trailing spaces from text columns

dataframes = [
    Customers_clean,
    Products_clean,
    Orders_clean,
    Order_details_clean,
    Targets_clean
]

for df in dataframes:
    text_columns = df.select_dtypes(include="object").columns

    for column in text_columns:
        df[column] = df[column].str.strip()

print("Text columns cleaned successfully")
print("Text columns cleaned successfully")

C:\Users\ANKIT PATEL\AppData\Local\Temp\ipykernel_23336\508313680.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns
C:\Users\ANKIT PATEL\AppData\Local\Temp\ipykernel_23336\508313680.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns
C:\Users\ANKIT PATEL\AppData\Local\Temp\ipykernel_23336\508313680.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns
C:\Users\ANKIT PATEL\AppData\Local\Temp\ipykernel_23336\508313680.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

Text columns cleaned successfully
Text columns cleaned successfully

C:\Users\ANKIT PATEL\AppData\Local\Temp\ipykernel_23336\508313680.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

Verify Text Cleaning

In [51]:
# Check for leading or trailing spaces

for name, df in {
    "Customers": Customers_clean,
    "Products": Products_clean,
    "Orders": Orders_clean,
    "Order Details": Order_details_clean,
    "Targets": Targets_clean
}.items():

    text_columns = df.select_dtypes(include="object").columns
    space_issues = 0

    for column in text_columns:
        space_issues += (
            df[column].dropna() != df[column].dropna().str.strip()
        ).sum()

    print(f"{name} space issues: {space_issues}")

C:\Users\ANKIT PATEL\AppData\Local\Temp\ipykernel_23336\2958541134.py:11: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns
C:\Users\ANKIT PATEL\AppData\Local\Temp\ipykernel_23336\2958541134.py:11: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns
C:\Users\ANKIT PATEL\AppData\Local\Temp\ipykernel_23336\2958541134.py:11: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

Customers space issues: 0
Products space issues: 0
Orders space issues: 0

C:\Users\ANKIT PATEL\AppData\Local\Temp\ipykernel_23336\2958541134.py:11: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

Order Details space issues: 0
Targets space issues: 0

C:\Users\ANKIT PATEL\AppData\Local\Temp\ipykernel_23336\2958541134.py:11: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

Step 13: Validate Business Rules

verify:

Gross_Sales = Quantity × Selling_Price

Discount_Amount = Gross_Sales × Discount

Net_Sales = Gross_Sales − Discount_Amount

Total_Cost = Quantity × Cost_Price

Profit = Net_Sales − Total_Cost

Check Gross Sales

In [53]:
# Calculate expected Gross Sales

expected_gross_sales = (
    Order_details_clean["Quantity"]
    * Order_details_clean["Selling_Price"]
)

gross_sales_errors = (
    (Order_details_clean["Gross_Sales"] - expected_gross_sales).abs() > 0.01
).sum()

print("Gross Sales Errors:", gross_sales_errors)

Gross Sales Errors: 0

Step 14: Validate Discount Amount

In [55]:
# Calculate expected Discount Amount

expected_discount_amount = (
    Order_details_clean["Gross_Sales"]
    * Order_details_clean["Discount"]
)

discount_errors = (
    (
        Order_details_clean["Discount_Amount"]
        - expected_discount_amount
    ).abs() > 0.01
).sum()

print("Discount Amount Errors:", discount_errors)

Discount Amount Errors: 0

Step 15: Validate Net Sales

In [56]:
# Calculate expected Net Sales

expected_net_sales = (
    Order_details_clean["Gross_Sales"]
    - Order_details_clean["Discount_Amount"]
)

net_sales_errors = (
    (
        Order_details_clean["Net_Sales"]
        - expected_net_sales
    ).abs() > 0.01
).sum()

print("Net Sales Errors:", net_sales_errors)

Net Sales Errors: 0

Step 16: Validate Total Cost

In [57]:
# Calculate expected Total Cost

expected_total_cost = (
    Order_details_clean["Quantity"]
    * Order_details_clean["Cost_Price"]
)

total_cost_errors = (
    (
        Order_details_clean["Total_Cost"]
        - expected_total_cost
    ).abs() > 0.01
).sum()

print("Total Cost Errors:", total_cost_errors)

Total Cost Errors: 0

Step 17: Validate Profit
Formula:

Profit = Net_Sales − Total_Cost

In [58]:
# Calculate expected Profit

expected_profit = (
    Order_details_clean["Net_Sales"]
    - Order_details_clean["Total_Cost"]
)

profit_errors = (
    (
        Order_details_clean["Profit"]
        - expected_profit
    ).abs() > 0.01
).sum()

print("Profit Errors:", profit_errors)

Profit Errors: 0

Step 18: Validate Profit Margin

Formula   :

Profit Margin = (Profit/Net Sales)*100

In [60]:
# Check Profit Margin values

display(
    Order_details_clean[
        ["Net_Sales", "Profit", "Profit_Margin"]
    ].head(10)
)

   Net_Sales  Profit  Profit_Margin
0     525.00  120.00       0.228571
1      50.00    5.00       0.100000
2     119.70   14.70       0.122807
3      34.00    9.00       0.264706
4      48.60   13.60       0.279835
5      95.00   10.00       0.105263
6      28.50    8.50       0.298246
7     360.00   65.00       0.180556
8     247.50   27.50       0.111111
9     166.25   51.25       0.308271

Step 18: Validate Profit Margin

In [62]:
# Calculate expected Profit Margin

expected_profit_margin = (
    Order_details_clean["Profit"]
    / Order_details_clean["Net_Sales"]
) * 100

# Handle zero Net Sales
expected_profit_margin = expected_profit_margin.fillna(0)

display(
    pd.DataFrame({
        "Existing Profit Margin": Order_details_clean["Profit_Margin"].head(10),
        "Expected Profit Margin": expected_profit_margin.head(10)
    })
)

   Existing Profit Margin  Expected Profit Margin
0                0.228571               22.857143
1                0.100000               10.000000
2                0.122807               12.280702
3                0.264706               26.470588
4                0.279835               27.983539
5                0.105263               10.526316
6                0.298246               29.824561
7                0.180556               18.055556
8                0.111111               11.111111
9                0.308271               30.827068

Check Profit Margin Errors

In [63]:
# Validate Profit Margin

profit_margin_errors = (
    (
        Order_details_clean["Profit_Margin"]
        - expected_profit_margin
    ).abs() > 0.01
).sum()

print("Profit Margin Errors:", profit_margin_errors)

Profit Margin Errors: 1012157

Compare Existing and Calculated Values

In [64]:
# Inspect Profit Margin values

margin_check = pd.DataFrame({
    "Net_Sales": Order_details_clean["Net_Sales"],
    "Profit": Order_details_clean["Profit"],
    "Existing_Margin": Order_details_clean["Profit_Margin"],
    "Calculated_Margin": expected_profit_margin
})

display(margin_check.head(10))

   Net_Sales  Profit  Existing_Margin  Calculated_Margin
0     525.00  120.00         0.228571          22.857143
1      50.00    5.00         0.100000          10.000000
2     119.70   14.70         0.122807          12.280702
3      34.00    9.00         0.264706          26.470588
4      48.60   13.60         0.279835          27.983539
5      95.00   10.00         0.105263          10.526316
6      28.50    8.50         0.298246          29.824561
7     360.00   65.00         0.180556          18.055556
8     247.50   27.50         0.111111          11.111111
9     166.25   51.25         0.308271          30.827068

Check Profit Margin Statistics

In [65]:
# Check Profit Margin range

print("Existing Profit Margin:")
print(Order_details_clean["Profit_Margin"].describe())

print("\nCalculated Profit Margin:")
print(expected_profit_margin.describe())

Existing Profit Margin:
count    1.019516e+06
mean     1.713145e-01
std      1.115975e-01
min     -3.492063e-01
25%      1.000000e-01
50%      1.700000e-01
75%      2.500000e-01
max      5.000000e-01
Name: Profit_Margin, dtype: float64

Calculated Profit Margin:
count    1.019516e+06
mean     1.713145e+01
std      1.115975e+01
min     -3.492063e+01
25%      1.000000e+01
50%      1.700000e+01
75%      2.500000e+01
max      5.000000e+01
dtype: float64

Check One Row Manually

In [66]:
# Manually calculate Profit Margin for the first row

row = Order_details_clean.iloc[0]

manual_margin = (
    row["Profit"] / row["Net_Sales"]
) * 100

print("Existing Margin:", row["Profit_Margin"])
print("Calculated Margin:", manual_margin)

Existing Margin: 0.228571429
Calculated Margin: 22.857142857142858

##  Problem

Profit_Margin values are stored as decimal values, not percentages.

Step 19: Correct Profit Margin Validation

In [67]:
# Calculate expected Profit Margin as a decimal

expected_profit_margin_decimal = (
    Order_details_clean["Profit"]
    / Order_details_clean["Net_Sales"]
).fillna(0)

# Compare with existing Profit_Margin

profit_margin_errors = (
    (
        Order_details_clean["Profit_Margin"]
        - expected_profit_margin_decimal
    ).abs() > 0.01
).sum()

print("Profit Margin Errors:", profit_margin_errors)

Profit Margin Errors: 0

Step 20: Data Quality Verification

In [68]:
# Data quality verification

datasets = {
    "Customers": Customers_clean,
    "Products": Products_clean,
    "Orders": Orders_clean,
    "Order Details": Order_details_clean,
    "Targets": Targets_clean
}

for name, df in datasets.items():
    print(f"\n{name}")
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Missing Values:", df.isna().sum().sum())
    print("Duplicate Rows:", df.duplicated().sum())

Customers
Rows: 10000
Columns: 7
Missing Values: 0
Duplicate Rows: 0

Products
Rows: 1392
Columns: 7
Missing Values: 0
Duplicate Rows: 0

Orders
Rows: 400000
Columns: 12
Missing Values: 0
Duplicate Rows: 0

Order Details
Rows: 1019516
Columns: 18
Missing Values: 0
Duplicate Rows: 0

Targets
Rows: 240
Columns: 4
Missing Values: 0
Duplicate Rows: 0

Step 21: Save Cleaned Datasets

In [70]:
# Save cleaned datasets

Customers_clean.to_csv(
    "../outputs/cleaned_customers.csv",
    index=False
)

Products_clean.to_csv(
    "../outputs/cleaned_products.csv",
    index=False
)

Orders_clean.to_csv(
    "../outputs/cleaned_orders.csv",
    index=False
)

Order_details_clean.to_csv(
    "../outputs/cleaned_order_details.csv",
    index=False
)

Targets_clean.to_csv(
    "../outputs/cleaned_targets.csv",
    index=False
)